name: build, make-dist, test

on: [push]

jobs:
  main:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1

    - name: autogen
      run: ./autogen.sh

    - name: configure
      run: ./configure --disable-manual

    - name: make
      run: make

    - name: test the checked-out source
      run: cd test && ./runtests

    - name: make dist
      run: make dist

    - name: unpack
      run: mkdir unpack && tar -C unpack -zxvf colm-*.tar.gz

    - name: configure the dist
      run: cd unpack/colm-* && ./configure --disable-manual

    - name: make from the dist
      run: cd unpack/colm-* && make

    - name: test the dist
      run: cd unpack/colm-*/test && ./runtests
